config/routes.rb
Rails.application.routes.draw do
  resources :mushrooms, only: [:index] do
    post 'search', on: :collection
    get 'search', on: :collection
  end
  root "mushrooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mushroom.rb
class Mushroom < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mushrooms_controller.rb
class MushroomsController < ApplicationController
  before_action :get_headers, :get_mushrooms

  def index
    render :index, locals: { mushrooms: @mushrooms }
  end

  def search
    cap_shapes = params['cap-shape'].select { |_key, value| value == '1' }.keys
    @mushrooms = Mushroom.where(cap_shape: cap_shapes)
    render :index, locals: { mushrooms: @mushrooms }
  end

  private

  def get_headers
    @headers = MushroomHelper.mushroom_attributes.first(5)
  end

  def get_mushrooms
    @mushrooms = MushroomHelper.mushrooms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mushroom_helper.rb
module MushroomHelper
  ATTRIBUTES = %w[
    cap-shape
    cap-surface
    cap-color
    bruises?
    odor
    gill-attachment
    gill-spacing
    gill-size
    gill-color
    stalk-shape
    stalk-root
    stalk-surface-above-ring
    stalk-surface-below-ring
    stalk-color-above-ring
    stalk-color-below-ring
    veil-type
    veil-color
    ring-number
    ring-type
    spore-print-color
    population
    habitat
  ].freeze

  ATTRIBUTE_MAPPING = "0. edible: edible=e',
  1. cap-shape: bell=b,conical=c,convex=x,flat=f, knobbed=k,sunken=s
2. cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s
3. cap-color: brown=n,buff=b,cinnamon=c,gray=g,green=r, pink=p,purple=u,red=e,white=w,yellow=y
4. bruises?: bruises=t,no=f
5. odor: almond=a,anise=l,creosote=c,fishy=y,foul=f,musty=m,none=n,pungent=p,spicy=s
6. gill-attachment: attached=a,descending=d,free=f,notched=n
7. gill-spacing: close=c,crowded=w,distant=d
8. gill-size: broad=b,narrow=n
9. gill-color: black=k,brown=n,buff=b,chocolate=h,gray=g, green=r,orange=o,pink=p,purple=u,red=e, white=w,yellow=y
10. stalk-shape: enlarging=e,tapering=t
11. stalk-root: bulbous=b,club=c,cup=u,equal=e,rhizomorphs=z,rooted=r
12. stalk-surface-above-ring: fibrous=f,scaly=y,silky=k,smooth=s
13. stalk-surface-below-ring: fibrous=f,scaly=y,silky=k,smooth=s
14. stalk-color-above-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o, pink=p,red=e,white=w,yellow=y
15. stalk-color-below-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o, pink=p,red=e,white=w,yellow=y
16. veil-type: partial=p,universal=u
17. veil-color: brown=n,orange=o,white=w,yellow=y
18. ring-number: none=n,one=o,two=t
19. ring-type: cobwebby=c,evanescent=e,flaring=f,large=l, none=n,pendant=p,sheathing=s,zone=z
20. spore-print-color: black=k,brown=n,buff=b,chocolate=h,green=r, orange=o,purple=u,white=w,yellow=y
21. population: abundant=a,clustered=c,numerous=n, scattered=s,several=v,solitary=y
22. habitat: grasses=g,leaves=l,meadows=m,paths=p, urban=u,waste=w,woods=d"

  def self.mushrooms
    Mushroom.all
  end

  def self.mushroom_attributes
    ATTRIBUTE_MAPPING.split(/\n/).map do |attr_string|
      header, codes = attr_string.tr('0-9', '').tr('. ', '').split(':')
      codes = codes.split(',')
      code_hash = {}
      codes.each do |code|
        sym, letter = code.split('=')
        code_hash[letter] = sym
      end
      { header: header, codes: code_hash }
    end
  end

  def self.mushroom_value(mushroom, header)
    mushroom[header[:header].gsub('-', '_').gsub('?', '')]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MushroomPicker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mushrooms/index.html.erb
<table>
  <thead>
  <tr>
    <% @headers.each do |attr| %>
      <th><%= attr[:header] %></th>
    <% end %>
  </tr>
  <tr>
    <%= form_tag search_mushrooms_path, method: :post do %>
      <% @headers.each do |attr| %>
        <th>
          <% attr[:codes].each do |code| %>
            <%= code[1] %>
            <%= check_box(attr[:header], code[0], checked: true) %>
          <% end %>
      <% end %>
      <%= submit_tag 'Filter' %>
      </th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <tr>
    <h3>Total mushrooms for query: <%= mushrooms.size %></h3>
  </tr>
  <% mushrooms.first(100).each do |mushroom| %>
    <tr>
      <% @headers.each do |header| %>
        <td><%= MushroomHelper.mushroom_value(mushroom, header) %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>